# Generated by Django 4.2.14 on 2024-11-08 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_content_message_messagemake'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='messagemake',
            new_name='message',
        ),
    ]
