# Generated by Django 4.2.14 on 2024-11-13 10:20

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_user_alter_message_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='link',
            field=models.CharField(default=app.models.generate_random_string, max_length=255, verbose_name='用户链接'),
        ),
    ]
