# Generated by Django 4.2.14 on 2024-11-13 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_user_link_user_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_money', models.FloatField(verbose_name='原金额')),
                ('money', models.FloatField(verbose_name='变更金额')),
                ('now_money', models.FloatField(verbose_name='现金额')),
                ('change_type', models.CharField(choices=[('管理员修改', '管理员修改'), ('下注扣除', '下注扣除'), ('中奖增加', '中奖增加')], max_length=255, verbose_name='变更原因')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
