# Generated by Django 4.2.14 on 2024-11-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_changemoney'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changemoney',
            name='change_type',
            field=models.CharField(choices=[('管理员修改', '管理员修改'), ('下注扣除', '下注扣除'), ('中奖增加', '中奖增加')], default='管理员修改', max_length=255, verbose_name='变更原因'),
        ),
    ]
