server:
  port: 8001

# 数据源配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://5.45.72.79:5400/process_bot?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: user_HHC7zR
    password: password_PpfikBkasdwqkcoq

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.li.bot.entity.database
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

bot:
#  botname: t.me/cha_info_china_bot # 机器人名称
#  token: 7478207741:AAHhv4pJ6oYnzThPGb_ZRk3BqENxcXk3hAQ # token
  botname: t.me/lidemobot # 机器人名称
  token: 8030696965:AAFY6eZti5yIg7J0p-mXIHSH9fLsmrvHBFE # token
  host: 127.0.0.1 #ip
  port: 7890    #端口
#  ${SERVER_HOST}
  url: https://d87a-111-55-96-176.ngrok-free.app/tgbot/process_bot #ngrok地址
  groupFile: workgroup.json
  channelFile: channel.json
