server:
  port: 8080

# 数据源配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/process_bot?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: postgres
    password: root

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.li.bot.entity.database
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

bot:
  botname: t.me/lidemobot # 机器人名称
  token: 8030696965:AAFY6eZti5yIg7J0p-mXIHSH9fLsmrvHBFE # token
  host: 127.0.0.1 #ip
  port: 7890    #端口
  url: https://497f-2409-8950-d43-1959-9c22-2ea6-15ba-7477.ngrok-free.app/webhook #ngrok地址
