# Generated by Django 4.2.14 on 2024-11-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_telegramusername_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramusername',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='img/', verbose_name='头像'),
        ),
    ]
