# Generated by Django 4.2.14 on 2024-11-29 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_telegramusername_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramusername',
            old_name='img',
            new_name='image',
        ),
    ]
