# Generated by Django 4.2.14 on 2024-12-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_telegramusername_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramusername',
            name='image',
            field=models.ImageField(blank=True, default='media/images/默认头像.png', null=True, upload_to='images/', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='telegramusername',
            name='username',
            field=models.CharField(max_length=100, unique=True, verbose_name='用户名'),
        ),
    ]
