# Generated by Django 4.2.14 on 2024-12-04 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_telegramusername_image_copytelegramuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copytelegramuser',
            name='copyObj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.telegramusername', verbose_name='复制用户'),
        ),
    ]
