# Generated by Django 4.2.14 on 2024-12-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_copytelegramuser_copyobj'),
    ]

    operations = [
        migrations.AddField(
            model_name='copytelegramuser',
            name='user_id',
            field=models.CharField(max_length=100, null=True, verbose_name='用户ID'),
        ),
    ]
