# Generated by Django 5.1.2 on 2024-12-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_copytelegramuser_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramusername',
            name='original_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='原头像'),
        ),
    ]
