# Generated by Django 5.1.2 on 2024-12-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_telegramusername_original_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramusername',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='名'),
        ),
        migrations.AddField(
            model_name='telegramusername',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='姓'),
        ),
    ]
