# Generated by Django 5.1.2 on 2024-10-31 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TgJoinGroup',
            fields=[
                ('join_group_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tg_id', models.BigIntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tg_join_group',
            },
        ),
        migrations.CreateModel(
            name='TgRecharge',
            fields=[
                ('recharge_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tg_id', models.BigIntegerField()),
                ('money', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tg_recharge',
            },
        ),
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('tg_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tg_full_name', models.CharField(max_length=50)),
                ('tg_username', models.CharField(blank=True, max_length=50, null=True)),
                ('money', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tg_user',
            },
        ),
    ]
