server:
  port: 8000

# 数据源配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: org.postgresql.Driver
    # ${DATABASE_BOT_HOST}
    url: jdbc:postgresql://${DATABASE_BOT_HOST}:${DATABASE_BOT_PORT}/publicity_bot_new?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: ${DATABASE_BOT_USERNAME}
    password: ${DATABASE_BOT_PASSWORD}

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.li.bot.entity.database
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

bot:
  botname: t.me/redianhutuibot # 机器人名称
  token: 8083224393:AAGPPVevhZ6VQr5GrVniEswayjh_6H3glTY # token
  host: 127.0.0.1 #ip
  port: 7890    #端口
  url: https://3d47-111-55-96-129.ngrok-free.app/tgbot/publicity_bot_new #ngrok地址
  adminChannelFile: adminChannel.json
  textFile: text.txt
  textBottomFile: textBottom.txt
